pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION = 'ap-south-1'
         PATH = "/opt/homebrew/bin:${env.PATH}" //optional
    }
    stages{
        stage('Checkout SCM'){
           steps{
                    git branch: 'main',
                    url: "https://github.com/kp820/Ecom_CD.git"
            }
        }
         stage('Initializing Terraform'){
            steps{
                script{
                    dir('CD_EKS'){
                         sh 'terraform init'
                    }
                }
            }
        }
        stage('Formating terraform code'){
            steps{
                script{
                    dir('CD_EKS'){
                         sh 'terraform fmt'
                    }
                }
            }
        }
        stage('Validating Terraform'){
            steps{
                script{
                    dir('CD_EKS'){
                         sh 'terraform validate'
                    }
                }
            }
        }
        stage('Previewing the infrastructure'){
            steps{
                script{
                    dir('CD_EKS'){
                         sh 'terraform plan'
                    }
                    input(message: "Are you sure to proceed?", ok: "proceed")
                }
            }
        }
        stage('Creating/Destroying an EKS cluster'){
            steps{
                script{
                    dir('CD_EKS'){
                         sh 'terraform $action --auto-approve'
                    }
                }
            }
        }
        stage("Deploying Ecom"){
            steps{
                script{
                    dir('CD_EKS/configuration-files'){
                        sh 'aws eks update-kubeconfig --name my-eks-cluster'
                        sh 'kubectl apply -f deployment.yml'
                        sh 'kubectl apply -f service.yml'
                    }
                }
            }
        }
    }
}
